version: '3.8'

services:
  app:
    image: golang:1.18-alpine  # Utilise une image Docker officielle pour Go
    container_name: go_dev_container
    init: true
    volumes:
      - .:/go/src/app  # Monte le répertoire de votre projet dans le conteneur
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /go/src/app
    command: sh -c "go mod tidy && go run main.go"  # Commande pour exécuter l'application Go
    ports:
      - "8080:8080"  # Expose le port de l'application
    environment:
      - GO111MODULE=on  # Active les modules Go
      - CGO_ENABLED=0  # Désactive CGO pour simplifier la compilation croisée

# Optionnel: Redis ou autre service nécessaire pour le développement
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

